# Generated by Django 4.0.5 on 2022-09-17 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_some'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Some',
        ),
    ]
