# Generated by Django 4.0.5 on 2022-08-06 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_car_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='engine',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
